---
printWidth: 100
tabWidth: 4
useTabs: true
trailingComma: all
semi: true
singleQuote: false

overrides:
    - files: "*.md"
      options:
          useTabs: false
    - files: "*.svelte"
      options:
          parser: svelte

plugins:
    - ./node_modules/@trivago/prettier-plugin-sort-imports/lib/src/index.js
    - ./node_modules/prettier-plugin-svelte/plugin.js
pluginSearchDirs: false

importOrder:
    - "^node:"
    - "^[^@.]"
    - "^@"
    - "^\\."
